// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using htmos.data;

#nullable disable

namespace htmos.data.migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260906010308_initialPostgreCreate")]
    partial class initialPostgreCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("htmos.model.Branch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "HQTRS"
                        });
                });

            modelBuilder.Entity("htmos.model.BranchAdmin", b =>
                {
                    b.Property<int>("BranchID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int?>("BranchID1")
                        .HasColumnType("integer");

                    b.Property<int>("ID")
                        .HasColumnType("integer");

                    b.HasKey("BranchID", "UserID");

                    b.HasIndex("BranchID1")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("BranchAdmins");
                });

            modelBuilder.Entity("htmos.model.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("BranchID")
                        .HasColumnType("integer");

                    b.Property<string>("Leader")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("BranchID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("htmos.model.Member", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("BranchID")
                        .HasColumnType("integer");

                    b.Property<int?>("BranchID1")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFirstTimer")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WorkerDepartmentID")
                        .HasColumnType("integer");

                    b.Property<int?>("WorkerMemberID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("BranchID");

                    b.HasIndex("BranchID1");

                    b.HasIndex("WorkerDepartmentID", "WorkerMemberID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("htmos.model.Permission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Read"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Write"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Branch.Write"
                        });
                });

            modelBuilder.Entity("htmos.model.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            ID = 2,
                            Name = "BranchAdmin"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Member"
                        });
                });

            modelBuilder.Entity("htmos.model.RolePermission", b =>
                {
                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionID")
                        .HasColumnType("integer");

                    b.HasKey("RoleID", "PermissionID");

                    b.HasIndex("PermissionID");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            PermissionID = 1
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 2
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 3
                        },
                        new
                        {
                            RoleID = 2,
                            PermissionID = 1
                        },
                        new
                        {
                            RoleID = 2,
                            PermissionID = 2
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 1
                        });
                });

            modelBuilder.Entity("htmos.model.Worker", b =>
                {
                    b.Property<int>("DepartmentID")
                        .HasColumnType("integer");

                    b.Property<int>("MemberID")
                        .HasColumnType("integer");

                    b.Property<int?>("BranchID")
                        .HasColumnType("integer");

                    b.Property<int>("ID")
                        .HasColumnType("integer");

                    b.HasKey("DepartmentID", "MemberID");

                    b.HasIndex("BranchID");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("producer.model.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "htm@hq.go",
                            Name = "Harvest Tabernacle Ministry",
                            Password = "pass-01",
                            Phone = "",
                            RoleID = 1
                        });
                });

            modelBuilder.Entity("htmos.model.BranchAdmin", b =>
                {
                    b.HasOne("htmos.model.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("htmos.model.Branch", null)
                        .WithOne("BranchAdmin")
                        .HasForeignKey("htmos.model.BranchAdmin", "BranchID1");

                    b.HasOne("producer.model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("htmos.model.Department", b =>
                {
                    b.HasOne("htmos.model.Branch", null)
                        .WithMany("Departments")
                        .HasForeignKey("BranchID");
                });

            modelBuilder.Entity("htmos.model.Member", b =>
                {
                    b.HasOne("htmos.model.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("htmos.model.Branch", null)
                        .WithMany("Members")
                        .HasForeignKey("BranchID1");

                    b.HasOne("htmos.model.Worker", null)
                        .WithMany("Members")
                        .HasForeignKey("WorkerDepartmentID", "WorkerMemberID");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("htmos.model.RolePermission", b =>
                {
                    b.HasOne("htmos.model.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("htmos.model.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("htmos.model.Worker", b =>
                {
                    b.HasOne("htmos.model.Branch", null)
                        .WithMany("Workers")
                        .HasForeignKey("BranchID");

                    b.HasOne("htmos.model.Department", "Department")
                        .WithMany("Workers")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("producer.model.User", b =>
                {
                    b.HasOne("htmos.model.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("htmos.model.Branch", b =>
                {
                    b.Navigation("BranchAdmin")
                        .IsRequired();

                    b.Navigation("Departments");

                    b.Navigation("Members");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("htmos.model.Department", b =>
                {
                    b.Navigation("Workers");
                });

            modelBuilder.Entity("htmos.model.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("htmos.model.Worker", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
