// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using htmos.data;

#nullable disable

namespace file_based_message_broker.data.migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260904135412_WorkersEntittyAdded")]
    partial class WorkersEntittyAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("htmos.model.Branch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "HQTRS"
                        });
                });

            modelBuilder.Entity("htmos.model.BranchAdmin", b =>
                {
                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int?>("BranchID1")
                        .HasColumnType("int");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.HasKey("BranchID", "UserID");

                    b.HasIndex("BranchID1")
                        .IsUnique()
                        .HasFilter("[BranchID1] IS NOT NULL");

                    b.HasIndex("UserID");

                    b.ToTable("BranchAdmins");
                });

            modelBuilder.Entity("htmos.model.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BranchID")
                        .HasColumnType("int");

                    b.Property<string>("Leader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BranchID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("htmos.model.Member", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int?>("BranchID1")
                        .HasColumnType("int");

                    b.Property<bool>("IsFirstTimer")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BranchID");

                    b.HasIndex("BranchID1");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("htmos.model.Permission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Read"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Write"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Branch.Write"
                        });
                });

            modelBuilder.Entity("htmos.model.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            ID = 2,
                            Name = "BranchAdmin"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Member"
                        });
                });

            modelBuilder.Entity("htmos.model.RolePermission", b =>
                {
                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int>("PermissionID")
                        .HasColumnType("int");

                    b.HasKey("RoleID", "PermissionID");

                    b.HasIndex("PermissionID");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            PermissionID = 1
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 2
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 3
                        },
                        new
                        {
                            RoleID = 2,
                            PermissionID = 1
                        },
                        new
                        {
                            RoleID = 2,
                            PermissionID = 2
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 1
                        });
                });

            modelBuilder.Entity("htmos.model.Worker", b =>
                {
                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int?>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.HasKey("DepartmentID", "MemberID");

                    b.HasIndex("BranchID");

                    b.HasIndex("MemberID");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("producer.model.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "htm@hq.go",
                            Name = "Harvest Tabernacle Ministry",
                            Password = "pass-01",
                            Phone = "",
                            RoleID = 1
                        });
                });

            modelBuilder.Entity("htmos.model.BranchAdmin", b =>
                {
                    b.HasOne("htmos.model.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("htmos.model.Branch", null)
                        .WithOne("BranchAdmin")
                        .HasForeignKey("htmos.model.BranchAdmin", "BranchID1");

                    b.HasOne("producer.model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("htmos.model.Department", b =>
                {
                    b.HasOne("htmos.model.Branch", null)
                        .WithMany("Departments")
                        .HasForeignKey("BranchID");
                });

            modelBuilder.Entity("htmos.model.Member", b =>
                {
                    b.HasOne("htmos.model.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("htmos.model.Branch", null)
                        .WithMany("Members")
                        .HasForeignKey("BranchID1");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("htmos.model.RolePermission", b =>
                {
                    b.HasOne("htmos.model.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("htmos.model.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("htmos.model.Worker", b =>
                {
                    b.HasOne("htmos.model.Branch", null)
                        .WithMany("Workers")
                        .HasForeignKey("BranchID");

                    b.HasOne("htmos.model.Department", "Department")
                        .WithMany("Workers")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("htmos.model.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("producer.model.User", b =>
                {
                    b.HasOne("htmos.model.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("htmos.model.Branch", b =>
                {
                    b.Navigation("BranchAdmin")
                        .IsRequired();

                    b.Navigation("Departments");

                    b.Navigation("Members");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("htmos.model.Department", b =>
                {
                    b.Navigation("Workers");
                });

            modelBuilder.Entity("htmos.model.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
